"""Build researched salon comparisons without rebuilding migrated content."""
from pathlib import Path
import re, json, html, xml.etree.ElementTree as ET
R = Path(__file__).resolve().parents[1]
D = 'https://www.craftcollectivesalongroup.com'
template = (R/'guides/first-salon-visit-checklist-pittsburgh/index.html').read_text()
records = []
def p(s): return '<p>'+s+'</p>'
def sec(h,s): return '<h2>'+h+'</h2>'+s
def ul(items): return '<ul>'+''.join('<li>'+i+'</li>' for i in items)+'</ul>'
def link(url,label): return '<a href="'+url+'">'+label+'</a>'
def publish(slug,title,description,body):
    path='guides/'+slug
    s=template
    s=re.sub(r'<title>.*?</title>','<title>'+html.escape(title)+'</title>',s,flags=re.S)
    for kind,name,val in [('name','description',description),('property','og:description',description),('property','og:title',title),('property','og:url',D+'/'+path)]:
        s=re.sub(r'(<meta '+kind+'="'+name+r'" content=")[^"]*(")',lambda m:m[1]+html.escape(val,quote=True)+m[2],s)
    s=re.sub(r'(<link rel="canonical" href=")[^"]*(")',lambda m:m[1]+D+'/'+path+m[2],s)
    hero='<header class="archive-hero"><p><a href="/">Home</a> / <a href="/guides">Salon guides</a> / <a href="/guides/pittsburgh-salon-alternatives">Salon comparisons</a></p><h1>'+html.escape(title)+'</h1><p class="archive-meta">Published by Craft Collective Salon Group · Sources checked October 1, 2026</p></header>'
    s=re.sub(r'<header class="archive-hero">.*?</header>',hero,s,flags=re.S)
    cta='<aside class="archive-cta"><h2>Explore Craft Collective</h2><p>Browse <a href="/hair-salon-gallery-pittsburgh">our work</a>, meet <a href="/meet-the-team">our stylists</a>, and read <a href="/reviews">client reviews</a>. Confirm your service, stylist, location and individual estimate before reserving.</p><p><a href="/book">Check booking options</a> or call <a href="tel:+17245147231">724-514-7231</a>.</p></aside>'
    s=re.sub(r'<article class="archive-body">.*?</article>','<article class="archive-body">'+body+cta+'</article>',s,flags=re.S)
    schema={'@context':'https://schema.org','@type':'Article','headline':title,'description':description,'mainEntityOfPage':D+'/'+path,'datePublished':'2026-10-01','dateModified':'2026-10-01','author':{'@type':'Organization','name':'Craft Collective Salon Group','url':D},'publisher':{'@type':'Organization','name':'Craft Collective Salon Group','url':D}}
    s=re.sub(r'<script type="application/ld\+json">.*?</script>','<script type="application/ld+json">'+json.dumps(schema).replace('</','<\\/')+'</script>',s,flags=re.S)
    f=R/path/'index.html';f.parent.mkdir(parents=True,exist_ok=True);f.write_text(s)
    records.append({'path':'/'+path,'title':title,'words':len(re.sub('<[^>]+>',' ',body).split())})

disclosure=p('This comparison is published by Craft Collective Salon Group. We have not tested or independently rated the other salon. Details come from the linked official pages checked October 1, 2026; menus, prices, staff and availability can change.')
craft=p('Craft Collective offers haircuts, balayage, highlights, blonding, extensions and smoothing services. Explore the '+link('/hair-services-pittsburgh','service menu')+' and individual '+link('/meet-the-team','stylist profiles')+'. Our locations are '+link('/locations/north-hills-pittsburgh','2014D Babcock Blvd in the North Hills')+' and '+link('/locations/canonsburg','115 W Pike St in Canonsburg')+'. Canonsburg is by appointment; confirm where your stylist works.')

publish('craft-collective-vs-studio-raw-elite','Craft Collective vs. Studio Raw Elite in Pittsburgh',
'Compare Craft Collective and Studio Raw Elite: Babcock Boulevard locations, hair color choices, salon setting and questions to ask before booking.',
p('Considering Studio Raw Elite or looking for another salon on Babcock Boulevard? Start with the stylist and appointment you need. Both salons describe hair color and haircut services, so a familiar service name alone will not tell you which reservation fits your goal.')+disclosure+
sec('Two Babcock Boulevard options',p('Studio Raw Elite lists its address as 3185 Babcock Boulevard, Pittsburgh, PA 15237. Its website describes a North Hills salon with an onsite café and deck, online booking and walk-in options. The menu includes dimensional color, hand-painted color, haircuts, barbering and texture services. See '+link('https://www.studiorawelite.com/','Studio Raw Elite’s official website')+' for current details.')+craft)+
sec('Compare the appointment, not just the label',p('If you want brightness through a brunette base, ask each stylist how they would place the light pieces and handle the root area. Bring a picture of your present hair in daylight and one or two examples of the result you want. Ask which appointment includes the finish shown in those photographs.')+ul(['Does the estimate include toner, root blending, haircut and blow-dry?','How much time should you reserve from arrival to departure?','What can be achieved on your current color, and what may need another visit?','Which stylist has examples similar to your starting hair?']))+
sec('Walk-in convenience or a planned transformation?',p('Studio Raw advertises walk-in options. Contact it to confirm whether the service and stylist you want can accommodate a walk-in that day. A major change needs enough reserved time regardless of which salon you choose. At Craft, check the booking options or call before selecting an unfamiliar color service.'))+
sec('When to consider Craft as an alternative',p('Craft is an option if you want to explore our color portfolio, compare our stylists or book at our Canonsburg location. Choose on the evidence that matters to you: relevant work, a clear consultation and a maintenance plan you can follow. Read our '+link('/reviews/color-and-extensions','color and extension review guide')+' and '+link('/blog/what-hair-color-service-to-book-pittsburgh','color booking guide')+' before reserving.')))

publish('craft-collective-vs-copacetic-beauty-lounge','Craft Collective vs. Copacetic Beauty Lounge',
'Compare two North Hills salon options: Craft Collective and Copacetic Beauty Lounge. Explore color estimates, extension consultations and salon fit.',
p('Looking at Copacetic Beauty Lounge and considering Craft Collective as another North Hills option? Compare how each salon explains your appointment and its ongoing cost. Your first color visit or extension installation is only one part of the plan.')+disclosure+
sec('What Copacetic highlights',p('Copacetic’s website describes a woman-owned North Hills salon, hourly color pricing, extension consultations, and hair-loss services including toppers and wigs. It also advertises same-day appointments, subject to availability. See '+link('https://www.copaceticpgh.com/','Copacetic’s official website')+' and '+link('https://www.copaceticpgh.com/color','its color service page')+'.')+craft)+
sec('Compare the total color estimate',p('An hourly price and a service-menu price cannot be compared fairly without knowing the time and inclusions. Ask for an estimated total for the same goal at each salon. Explain your previous color, density, length and the change you want. Then ask what could change that estimate during consultation.')+ul(['Are application and processing time both included in the estimate?','Are toner, finishing and any haircut included?','Does the plan involve one appointment or several?','What follow-up services should you budget for?']))+
sec('Extensions: ask about the whole cycle',p('Bring your desired length and fullness to the consultation, then discuss the hair purchase, installation, maintenance appointments and eventual removal. Confirm the method and who will maintain it. Ask to see work on hair with similar density to yours. A method name or introductory estimate does not establish the full ongoing commitment.')+p('Our '+link('/blog/hair-extensions-budget-pittsburgh','extension budget guide')+' provides a checklist to use when comparing quotes. Craft’s '+link('/services/hair-extensions-pittsburgh','extension page')+' explains how to begin with a consultation.'))+
sec('Hair-loss needs deserve a specific conversation',p('Copacetic advertises hair-loss services. If toppers, wigs or a private consultation are central to your search, ask it directly about those offerings. Do not assume another salon offers the same services because it provides extensions. Ask Craft about your particular goal before booking.'))+
sec('Explore Craft’s work before deciding',p('Consider Craft when our stylist portfolio, salon location and consultation approach fit the result you want. View '+link('/hair-salon-gallery-pittsburgh','our gallery')+' and '+link('/reviews','client feedback')+', then confirm your individual estimate.')))

publish('craft-collective-vs-salon-13','Craft Collective vs. Salon 13: Pittsburgh Salon Options',
'Compare Craft Collective and Salon 13 around Pittsburgh: location, stylist portfolios, booking details and a checklist for your next hair appointment.',
p('Choosing between Salon 13 and Craft Collective? Begin with where you want to go and the individual stylist whose work matches your goal. A salon’s overall reputation can help you create a shortlist, but the consultation should settle the details of your appointment.')+disclosure+
sec('Location and booking',p('Salon 13 lists 2400 Ferguson Road, Allison Park, PA 15101. Its contact page offers online and telephone booking and publishes cancellation terms. Its team page includes stylist biographies and portfolio links. Check '+link('https://www.salon13.net/contact/','Salon 13’s current booking information')+' and '+link('https://www.salon13.net/our-team/','its stylist team')+'.')+craft)+
sec('Match the portfolio to your starting hair',p('For a short haircut, look for examples with a comparable outline and texture. For blonde or dimensional color, compare the starting shade, root appearance and finish. A picture of a result on very different hair may be useful inspiration, but it is not a promise of what one appointment will produce.')+ul(['Can the stylist describe how the inspiration photo relates to your hair?','What length, weight or color would need to change?','How will the style look when you wear it your usual way?','Which follow-up appointment keeps the result close to the photograph?']))+
sec('Read appointment policies before reserving',p('Confirm cancellation and rescheduling terms directly with the salon you book. Also check whether your reservation includes every service you want. Adding or dropping a color service at the appointment can affect the time reserved. If your plan changes, contact the salon in advance instead of relying on the service name in a comparison article.'))+
sec('Changing salons for a new cut or color',p('A new stylist will need your recent hair history, including at-home color and chemical treatments. Explain what you liked about previous appointments as well as what you want to change. You can ask for a new shape while preserving the color you enjoy, or change the color while keeping your current length.')+p('Use our '+link('/guides/switching-hair-salons-pittsburgh','switching salons checklist')+' to prepare. Craft’s '+link('/reviews/haircuts-and-curls','haircut and curl review guide')+' and '+link('/reviews/color-and-extensions','color review guide')+' offer another way to explore our work.'))+
sec('When Craft may suit your shortlist',p('Explore Craft if you want to compare our stylist portfolios or prefer our North Hills or Canonsburg location. Bring your desired result and budget to the consultation, then decide using the proposed service, expected upkeep and actual appointment availability.')))

publish('craft-collective-vs-bloom-beauty-parlor','Craft Collective vs. BLOOM Beauty Parlor in Pittsburgh',
'Compare Craft Collective and BLOOM Beauty Parlor: North Hills, Canonsburg and East Liberty locations, salon priorities and appointment planning.',
p('Looking for an alternative to BLOOM Beauty Parlor, or deciding whether to travel between East Liberty and the North Hills for your hair appointment? Consider both the result and the routine. A salon you can return to comfortably may be a better fit for frequent maintenance.')+disclosure+
sec('Which BLOOM does this page cover?',p('This page refers to BLOOM Beauty Parlor at 214 N. Highland Avenue in East Liberty. Its website emphasizes sustainability, cruelty-free practices and an inclusive setting, with online booking and text help choosing a service. See '+link('https://bloombeautyparlor.com/','BLOOM Beauty Parlor’s official website')+'. Other businesses also use the name Bloom; confirm the address before reserving.')+craft)+
sec('Neighborhood convenience and upkeep',p('Think beyond the first appointment when choosing a location. Ask how often your color, haircut or extensions may need salon maintenance, then consider the travel that schedule creates. Check the salon’s current hours and any parking or access details directly before your visit. We have not measured route times between these salons.')+ul(['Can you return for the recommended maintenance appointments?','Does the chosen stylist work at the location you intend to visit?','How much appointment time can you reserve alongside travel?','Would a smaller refresh fit your schedule better than a major change?']))+
sec('Ask about the salon practices you value',p('If environmental practices or product preferences shape your choice, ask each salon what those practices mean for the service you want. Discuss the products involved, any preferences you have and what the salon can accommodate. We do not claim Craft has the same sustainability certifications or practices as BLOOM.'))+
sec('Compare color plans with the same brief',p('Give each stylist the same starting information: your recent hair history, desired tone, budget and maintenance preference. Ask what is included in the estimate and whether the plan needs several visits. A consultation lets you compare proposed work instead of assuming that similarly named services are identical.')+p('Explore '+link('/guides/hair-color-comparisons-pittsburgh','our color comparison guide')+' and '+link('/guides/low-maintenance-color-alternatives','lower-maintenance color options')+' to prepare your questions.'))+
sec('When to explore Craft as an alternative',p('Craft may belong on your shortlist if our North Hills or Canonsburg location works for you and you like the work in our gallery. Review individual stylist profiles and confirm the appointment plan. Choose the combination of work, setting and maintenance that fits your priorities.')))

publish('switching-hair-salons-pittsburgh','Switching Hair Salons in Pittsburgh: A Practical Checklist',
'Changing Pittsburgh salons? Prepare your hair history, photos, budget and questions so a new stylist can plan your haircut, color or extensions.',
p('Changing salons can be a practical choice when your schedule, location, budget or hair goals change. Before booking a new Pittsburgh stylist, write down what you want to keep and what you want to change. That gives the first consultation a clearer starting point.')+
sec('Bring the history behind your current hair',ul(['When was your most recent cut and color, and what was done?','Have you used at-home dye, lightener, henna or direct color?','Have you had smoothing treatments or other chemical services?','Do you currently wear extensions, and what method and maintenance do they require?','What styling tools and products do you regularly use?'])+p('If you know your previous formula or extension details, bring them. If you do not, say so. Avoid guessing product names or concealing at-home color; the stylist needs accurate information to plan the work.'))+
sec('Separate a new stylist from a complete transformation',p('You can change salons and keep the shape or shade you already like. Describe the parts that work: the length around your face, your root tone or how your hair behaves between washes. Then name the specific issue you want help with. A targeted adjustment may require a different reservation from a full transformation.'))+
sec('Ask for the plan and estimate before booking',ul(['Which service should I reserve for this starting point and goal?','What is included in the estimated total?','How long should I allow for the complete appointment?','What may need to happen over more than one visit?','What follow-up visits and home routine should I expect?'])+p('Confirm the stylist, address and current policies. If you need help choosing a Craft appointment, call 724-514-7231 rather than selecting an unfamiliar service solely by its name.'))+
sec('Use comparisons to make a shortlist',p('Our '+link('/guides/pittsburgh-salon-alternatives','Pittsburgh salon alternatives guide')+' links to researched comparisons. Use those pages to identify questions and location differences, then check availability directly. A published comparison does not replace a conversation with the person who will perform your service.'))+
sec('Prepare for the first visit',p('Bring daylight photographs of your current hair and a few examples of your goal. Explain how you normally wear your hair and how much time you spend styling it. After consultation, agree on the service and estimate before proceeding. See our '+link('/guides/first-salon-visit-checklist-pittsburgh','first-visit checklist')+' and '+link('/blog/salon-consultation-photos-pittsburgh','inspiration-photo guide')+' for more preparation ideas.')))

comparisons=list(records[:4])
publish('pittsburgh-salon-alternatives','Pittsburgh Salon Alternatives & Comparisons | Craft Collective',
'Compare Craft Collective with Studio Raw Elite, Copacetic, Salon 13 and BLOOM Beauty Parlor. Plan by location, hair goals and consultation questions.',
p('Searching for a Pittsburgh hair salon alternative? Start with the reason for your search: a different location, a new stylist, another color approach or a schedule that fits your life. The most useful comparison answers that need and helps you ask better questions before booking.')+
p('This guide is published by Craft Collective Salon Group. It is a starting point for your shortlist, with links to other salons’ official information. We have not independently tested or ranked these businesses.')+
sec('Compare Craft with local salon options',ul([link(r['path'],r['title']) for r in comparisons]))+
sec('Choose the comparison that matches your question',ul(['Comparing Babcock Boulevard options? Start with the Studio Raw Elite comparison.','Comparing color estimates or extension budgets? Read the Copacetic comparison.','Looking around Allison Park and the North Hills? Explore the Salon 13 comparison.','Choosing between East Liberty and a North Hills or Canonsburg appointment? Read the BLOOM Beauty Parlor comparison.']))+
sec('Use the same appointment brief at each salon',p('Write down your present hair, desired result, budget and preferred upkeep. Share the same information when asking for an estimate. Confirm the included services, total reserved time and follow-up plan. A price comparison is more useful when both estimates describe comparable work.')+
p('Look at stylist portfolios with examples close to your starting hair. Review recent feedback, but read what the review says about the particular service rather than choosing solely by a headline rating.'))+
sec('Compare services as well as salons',p('If you are unsure what to book, explore '+link('/guides/hair-color-comparisons-pittsburgh','color options')+', '+link('/guides/hair-extension-comparisons-pittsburgh','extension options')+' and '+link('/guides/low-maintenance-color-alternatives','lower-maintenance color alternatives')+'. The best next step may be a consultation about your goal before choosing a technique.'))+
sec('Explore Craft’s locations and work',craft+p('Browse '+link('/hair-salon-gallery-pittsburgh','the gallery')+', '+link('/reviews','client reviews')+' and '+link('/guides/switching-hair-salons-pittsburgh','our switching-salons checklist')+'. Sources for the comparisons were checked October 1, 2026. Contact each salon to verify current services, policies and availability.')))

# Add discovery links to existing hubs; preserve all other content.
for target in ['guides/index.html','blog/index.html','hair-services-pittsburgh/index.html']:
    f=R/target;s=f.read_text()
    s=re.sub(r'<!-- cc:saloncomparisons -->.*?<!-- /cc:saloncomparisons -->','',s,flags=re.S)
    block='<section class="archive-body" aria-labelledby="salon-comparisons"><h2 id="salon-comparisons">Compare Pittsburgh salon options</h2><p><a href="/guides/pittsburgh-salon-alternatives">Explore local salon comparisons and alternatives</a>, or prepare with our <a href="/guides/switching-hair-salons-pittsburgh">switching salons checklist</a>.</p></section>'
    wrapped='<!-- cc:saloncomparisons -->'+block+'<!-- /cc:saloncomparisons -->'
    if '</main>' in s:s=s.replace('</main>',wrapped+'</main>',1)
    else:s=s.replace('<footer',wrapped+'<footer',1)
    assert wrapped in s,target
    if target=='guides/index.html':
        desc='Plan your Pittsburgh salon visit with service comparisons, local salon alternatives, booking checklists and guides from Craft Collective.'
        for kind,name in [('name','description'),('property','og:description')]:
            s=re.sub(r'(<meta '+kind+'="'+name+r'" content=")[^"]*(")',lambda m:m[1]+desc+m[2],s)
    f.write_text(s)

NS='http://www.sitemaps.org/schemas/sitemap/0.9';ET.register_namespace('',NS)
f=R/'site-pages-sitemap.xml';tree=ET.parse(f);root=tree.getroot()
known={e.text for e in root.findall('.//{'+NS+'}loc')}
for r in records:
    if D+r['path'] not in known:
        e=ET.SubElement(root,'{'+NS+'}url');ET.SubElement(e,'{'+NS+'}loc').text=D+r['path'];ET.SubElement(e,'{'+NS+'}lastmod').text='2026-10-01'
tree.write(f,encoding='UTF-8',xml_declaration=True)
(R/'scripts/salon-comparisons-manifest.json').write_text(json.dumps({'pages':records,'source_date':'2026-10-01','sources':['https://www.studiorawelite.com/','https://www.copaceticpgh.com/','https://www.copaceticpgh.com/color','https://www.salon13.net/contact/','https://www.salon13.net/our-team/','https://bloombeautyparlor.com/']},indent=2)+'\n')
print(json.dumps(records,indent=2))
